version: 0.2

env:
  variables:
    REPOSITORY_TAG: $REPOSITORY_TAG
    REPOSITORY_URI: $REPOSITORY_URI
    DOCKER_USER: $DOCKER_USER
    DOCKER_PASS: $DOCKER_PASS
    SASS_PATH: $SASS_PATH
    REACT_APP_STAGE: $REACT_APP_STAGE
    REACT_APP_GTM_ID: $REACT_APP_GTM_ID
    REACT_APP_GTM_AUTH: $REACT_APP_GTM_AUTH
    REACT_APP_GTM_PREVIEW: $REACT_APP_GTM_PREVIEW
    REACT_APP_PRISMIC_REPOSITORY: $REACT_APP_PRISMIC_REPOSITORY
    REACT_APP_PRISMIC_ACCESS_TOKEN: $REACT_APP_PRISMIC_ACCESS_TOKEN
    REACT_APP_ONE_SIGNAL_APP_ID: $REACT_APP_ONE_SIGNAL_APP_ID
    REACT_APP_ROLLBAR_ACCESS_TOKEN: $REACT_APP_ROLLBAR_ACCESS_TOKEN
    REACT_APP_SENDBIRD_API_ID: $REACT_APP_SENDBIRD_API_ID
    REACT_APP_SENDBIRD_ACCESS_TOKEN: $REACT_APP_SENDBIRD_ACCESS_TOKEN
    REACT_APP_USER_POOL_ID: $REACT_APP_USER_POOL_ID
    REACT_APP_USER_POOL_WEB_CLIENT_ID: $REACT_APP_USER_POOL_WEB_CLIENT_ID
    REACT_APP_BASE_URL: $REACT_APP_BASE_URL
    REACT_APP_API_VERSION: $REACT_APP_API_VERSION
    REACT_APP_API_KEY: $REACT_APP_API_KEY
    REACT_APP_CAPTCHA_CLIENT_SITE_KEY: $REACT_APP_CAPTCHA_CLIENT_SITE_KEY

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=$REPOSITORY_TAG}
      - docker login --username $DOCKER_USER -p $DOCKER_PASS
      - yarn install
  build:
    commands:
      - echo Build started on `date`
      - yarn run build
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:$REPOSITORY_TAG .
      - docker tag $REPOSITORY_URI:$REPOSITORY_TAG $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:$REPOSITORY_TAG
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"container-name","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
    files: imagedefinitions.json
cache:
  paths:
    - '/root/.yarn-cache/**/*'
    - 'node_modules/**/*'
