version: "3"

services:

  container-name:
    image: # repositoryurl:tag
    ports:
      - "0:3000"
    logging:
      driver: awslogs
      options:
        awslogs-group: # group name
        awslogs-region: ap-southeast-1
        awslogs-stream-prefix: ecs
